apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Start 1 new pod before killing the old one (Create the new pod first)
      maxUnavailable: 0 # Never allow more than 0 pod to be down (DO NOT kill the old pod until the new one is 'Ready')

  template:
    metadata:
      labels:
        app: order-app

    spec:
      nodeSelector:
        worker-type: "worker"
      containers:
        - name: order-service
          image: barun25/choreography-saga-order-service:latest
          imagePullPolicy: Always

          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER

            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS

            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_HOST

            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PORT

            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)/

          ports:
            - containerPort: 4001

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

